name: smishing


channels:
  - conda-forge
  - pytorch
  - nvidia
  - main

dependencies:

  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm

  - python
  - pip
  - jupyter
  - ipywidgets

  # Data Work
  - pandas
  - pyarrow
  - numpy

  # PyTorch
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - pytorch-cuda=11.8 # My GPU is a 1070 which is on CUDA 11.8

  # HuggingFace
  - transformers

  # Formating
  - black
  - flake8
  - isort
  - typer
  - loguru
  - tqdm

  # NLP work
  - nltk
  - scikit-learn

  # Web scraping
  - requests
  - beautifulsoup4

  # PDF scraping
  - pypdf2

  - pdfminer.six

  - pip:
    - python-dotenv
    - pymupdf  #PDF Scraping
    - lxml # Excel files and pandas

    # Model Interpretation
    - lime
    - shape
    - -e .  # Install the setup file



  # - pip:
  #   # - python-dotenv
  #   - -e .